name: Android PR CI

on:
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'android/**'

defaults:
  run:
    working-directory: ./android

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/test-results/**/*.xml"
  notification:
      name: Notification
      runs-on: ubuntu-latest
      if: ${{ always() }}
      needs: [unit_test]
      steps:
        - uses: martialonline/workflow-status@v3
          id: check
        - name: action-slack
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ steps.check.outputs.status }}
            author_name: Github Action Bot
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always() 
