name: Android PR CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'corretto'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Access HOLIDAY_API_KEY
        env:
          HOLIDAY_API_KEY: $
        run: echo HOLIDAY_API_KEY=\"$HOLIDAY_API_KEY\" > ./local.properties

      - name: Access KAKAO_NATIVE_APP_KEY
        env:
          KAKAO_NATIVE_APP_KEY: $
        run: echo KAKAO_NATIVE_APP_KEY=\"$KAKAO_NATIVE_APP_KEY\" > ./local.properties

      - name: Access DATASTORE_NAME
        env:
          DATASTORE_NAME: $
        run: echo DATASTORE_NAME=\"$DATASTORE_NAME\" > ./local.properties

      - name: Access BASE_URL
        env:
          DATASTORE_NAME: $
        run: echo BASE_URL=\"$BASE_URL\" > ./local.properties

      - name: Build with Gradle
        run: ./gradlew build

  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/test-results/**/*.xml"

  notification:
      name: Notification
      runs-on: ubuntu-latest
      if: ${{ always() }}
      needs: [unit_test]
      steps:
        - uses: martialonline/workflow-status@v3
          id: check
        - name: action-slack
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ steps.check.outputs.status }}
            author_name: Github Action Bot
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always()
